# Generated by Django 5.2.17 on 2026-09-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_allow_blank_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('password_reset', 'Password Reset'), ('activation', 'Activation')], max_length=32)),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the raw emailed token. Never the token itself.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='identity_em_expires_5b6c2d_idx'), models.Index(fields=['user', 'purpose'], name='identity_em_user_id_eeb696_idx')],
            },
        ),
    ]
