# Generated by Django 5.2.17 on 2026-10-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_emailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_key',
            field=models.CharField(blank=True, help_text='Storage key of the profile photo (see identity.avatars); empty for none.', max_length=255),
        ),
    ]
