# Generated by Django 5.2.17 on 2026-10-03 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0006_idea_submission_context_constraints'),
        ('reviews', '0003_review_scope_and_platform_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('idea.organization_changes_requested', 'Changes requested by your organization'), ('idea.organization_confirmed', 'Your organization confirmed your idea'), ('idea.submitted_to_platform', 'Your idea was submitted to the platform'), ('idea.platform_changes_requested', 'The platform asked for changes'), ('idea.platform_rejected', 'The platform did not approve your idea'), ('idea.platform_approved', 'Platform review completed'), ('idea.owner_go_ahead', 'Your idea is ready for implementation'), ('review.assigned', 'An idea was assigned to you'), ('review.organization_queue', 'An idea is waiting for organization review'), ('review.platform_queue', 'An idea is waiting for platform review'), ('invitation.received', 'You have been invited'), ('invitation.accepted', 'Your invitation was accepted'), ('message.received', 'You have a new message')], max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(help_text='A short, non-sensitive summary. The full content stays behind authentication.', max_length=500)),
                ('is_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='ideas.idea')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reviews.platformreviewreport')),
                ('user', models.ForeignKey(help_text='The person being told.', on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notif_user_created_idx'), models.Index(fields=['user', 'is_read_at', '-created_at'], name='notif_unread_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', {'idea.organization_changes_requested': 'Changes requested by your organization', 'idea.organization_confirmed': 'Your organization confirmed your idea', 'idea.owner_go_ahead': 'Your idea is ready for implementation', 'idea.platform_approved': 'Platform review completed', 'idea.platform_changes_requested': 'The platform asked for changes', 'idea.platform_rejected': 'The platform did not approve your idea', 'idea.submitted_to_platform': 'Your idea was submitted to the platform', 'invitation.accepted': 'Your invitation was accepted', 'invitation.received': 'You have been invited', 'message.received': 'You have a new message', 'review.assigned': 'An idea was assigned to you', 'review.organization_queue': 'An idea is waiting for organization review', 'review.platform_queue': 'An idea is waiting for platform review'})), name='notification_kind_is_known'), models.CheckConstraint(condition=models.Q(('report_id__isnull', True), ('idea_id__isnull', False), _connector='OR'), name='notification_report_needs_idea')],
            },
        ),
    ]
