# Generated by Django 5.2.17 on 2026-10-05 08:37

from django.conf import settings
"""
`invitation.declined` joins the notification vocabulary.

**Additive.** One more value in the CHECK constraint's allowed set, and a
migration that widens it in place. No existing notification is rewritten: a row
already delivered keeps the kind it was delivered with, which is the point of
storing the kind as a string rather than resolving it from today's vocabulary.

Nothing here makes the kind *possible* - `invitations.services
._notify_inviter_of_decline` does that, and it writes the row through
`notifications.services.deliver` like every other kind.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_idea_team_visibility'),
        ('notifications', '0001_initial'),
        ('reviews', '0004_review_rounds_per_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_kind_is_known',
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('idea.organization_changes_requested', 'Changes requested by your organization'), ('idea.organization_confirmed', 'Your organization confirmed your idea'), ('idea.submitted_to_platform', 'Your idea was submitted to the platform'), ('idea.platform_changes_requested', 'The platform asked for changes'), ('idea.platform_rejected', 'The platform did not approve your idea'), ('idea.platform_approved', 'Platform review completed'), ('idea.owner_go_ahead', 'Your idea is ready for implementation'), ('review.assigned', 'An idea was assigned to you'), ('review.organization_queue', 'An idea is waiting for organization review'), ('review.platform_queue', 'An idea is waiting for platform review'), ('invitation.received', 'You have been invited'), ('invitation.accepted', 'Your invitation was accepted'), ('invitation.declined', 'Your invitation was declined'), ('message.received', 'You have a new message')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', {'idea.organization_changes_requested': 'Changes requested by your organization', 'idea.organization_confirmed': 'Your organization confirmed your idea', 'idea.owner_go_ahead': 'Your idea is ready for implementation', 'idea.platform_approved': 'Platform review completed', 'idea.platform_changes_requested': 'The platform asked for changes', 'idea.platform_rejected': 'The platform did not approve your idea', 'idea.submitted_to_platform': 'Your idea was submitted to the platform', 'invitation.accepted': 'Your invitation was accepted', 'invitation.declined': 'Your invitation was declined', 'invitation.received': 'You have been invited', 'message.received': 'You have a new message', 'review.assigned': 'An idea was assigned to you', 'review.organization_queue': 'An idea is waiting for organization review', 'review.platform_queue': 'An idea is waiting for platform review'})), name='notification_kind_is_known'),
        ),
    ]
