# Generated by Django 5.2.17 on 2026-10-06 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_idea_team_visibility'),
        ('notifications', '0002_invitation_declined_kind'),
        ('reviews', '0004_review_rounds_per_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_kind_is_known',
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('idea.organization_changes_requested', 'Changes requested by your organization'), ('idea.organization_confirmed', 'Your organization confirmed your idea'), ('idea.submitted_to_platform', 'Your idea was submitted to the platform'), ('idea.platform_changes_requested', 'The platform asked for changes'), ('idea.platform_rejected', 'The platform did not approve your idea'), ('idea.platform_approved', 'Platform review completed'), ('idea.owner_go_ahead', 'Your idea is ready for implementation'), ('automation.opportunity_created', 'An automation opportunity was opened'), ('automation.requirements_ready', 'Requirements are ready'), ('automation.proposal_submitted', 'A proposal was submitted'), ('automation.proposal_changes_requested', 'Changes were requested on a proposal'), ('automation.ready_for_assignment', 'An opportunity is ready for assignment'), ('automation.opportunity_assigned', 'An opportunity was assigned'), ('automation.project_created', 'A project was created'), ('automation.project_started', 'A project has started'), ('automation.ready_for_uat', 'A project is ready for acceptance testing'), ('automation.testing_failed', 'A required test failed'), ('automation.uat_passed', 'Acceptance testing passed'), ('automation.uat_failed', 'Acceptance testing failed'), ('automation.deployment_completed', 'A deployment completed'), ('automation.milestone_completed', 'A milestone was completed'), ('automation.project_completed', 'A project was completed'), ('automation.impact_recorded', 'Impact was recorded'), ('review.assigned', 'An idea was assigned to you'), ('review.organization_queue', 'An idea is waiting for organization review'), ('review.platform_queue', 'An idea is waiting for platform review'), ('invitation.received', 'You have been invited'), ('invitation.accepted', 'Your invitation was accepted'), ('invitation.declined', 'Your invitation was declined'), ('message.received', 'You have a new message')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', {'automation.deployment_completed': 'A deployment completed', 'automation.impact_recorded': 'Impact was recorded', 'automation.milestone_completed': 'A milestone was completed', 'automation.opportunity_assigned': 'An opportunity was assigned', 'automation.opportunity_created': 'An automation opportunity was opened', 'automation.project_completed': 'A project was completed', 'automation.project_created': 'A project was created', 'automation.project_started': 'A project has started', 'automation.proposal_changes_requested': 'Changes were requested on a proposal', 'automation.proposal_submitted': 'A proposal was submitted', 'automation.ready_for_assignment': 'An opportunity is ready for assignment', 'automation.ready_for_uat': 'A project is ready for acceptance testing', 'automation.requirements_ready': 'Requirements are ready', 'automation.testing_failed': 'A required test failed', 'automation.uat_failed': 'Acceptance testing failed', 'automation.uat_passed': 'Acceptance testing passed', 'idea.organization_changes_requested': 'Changes requested by your organization', 'idea.organization_confirmed': 'Your organization confirmed your idea', 'idea.owner_go_ahead': 'Your idea is ready for implementation', 'idea.platform_approved': 'Platform review completed', 'idea.platform_changes_requested': 'The platform asked for changes', 'idea.platform_rejected': 'The platform did not approve your idea', 'idea.submitted_to_platform': 'Your idea was submitted to the platform', 'invitation.accepted': 'Your invitation was accepted', 'invitation.declined': 'Your invitation was declined', 'invitation.received': 'You have been invited', 'message.received': 'You have a new message', 'review.assigned': 'An idea was assigned to you', 'review.organization_queue': 'An idea is waiting for organization review', 'review.platform_queue': 'An idea is waiting for platform review'})), name='notification_kind_is_known'),
        ),
    ]
