# Generated by Django 5.2.17 on 2026-10-03 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_idea_review_permission_and_reviewer_role'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('organization', 'Organization'), ('team', 'Team')], default='organization', max_length=16)),
                ('email', models.CharField(db_index=True, max_length=254)),
                ('role_slug', models.CharField(help_text="The tenant's role slug this invitation grants, resolved on acceptance.", max_length=100)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(help_text='The member who sent this invitation.', on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='inv_org_status_idx'), models.Index(fields=['team', 'status', '-created_at'], name='inv_team_status_idx'), models.Index(fields=['email', 'status'], name='inv_email_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization_id__isnull', False), ('scope', 'organization'), ('team_id__isnull', True)), models.Q(('organization_id__isnull', True), ('scope', 'team'), ('team_id__isnull', False)), _connector='OR'), name='invitation_scope_matches_tenant'), models.CheckConstraint(condition=models.Q(('status__in', {'accepted': 'Accepted', 'expired': 'Expired', 'pending': 'Pending', 'revoked': 'Revoked'})), name='invitation_status_is_known'), models.CheckConstraint(condition=models.Q(('scope__in', {'organization': 'Organization', 'team': 'Team'})), name='invitation_scope_is_known'), models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', False), ('accepted_by__isnull', False), ('status', 'accepted')), models.Q(('status', 'accepted'), _negated=True), _connector='OR'), name='invitation_accepted_iff_recorded')],
            },
        ),
    ]
