# Generated by Django 5.2.17 on 2026-10-05 08:36

import django.db.models.deletion
"""
A recipient can decline an invitation.

**No data moves and no existing invitation changes state.** This migration adds
two columns (`declined_by`, `declined_at`), widens the status CHECK to include
`declined`, and adds a constraint pairing that status with the two columns.

Existing rows keep `status='pending' | 'accepted' | 'expired' | 'revoked'` and
leave both new columns null, which the new constraint requires - so it is
satisfied by every row that exists before the migration runs. Nothing here
infers a decline from an expired or revoked invitation: those are different
facts, and guessing would tell an inviter somebody said no when in fact nobody
did.

Safe against a populated database for the same reason the ideas migration was:
the old CHECK is removed and the new one added within one migration, so no
intermediate state exists in which a row could be invalid.
"""

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        ('organizations', '0003_idea_review_permission_and_reviewer_role'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='invitation_status_is_known',
        ),
        migrations.AddField(
            model_name='invitation',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declined_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('declined', 'Declined')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'accepted': 'Accepted', 'declined': 'Declined', 'expired': 'Expired', 'pending': 'Pending', 'revoked': 'Revoked'})), name='invitation_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('declined_at__isnull', False), ('declined_by__isnull', False), ('status', 'declined')), models.Q(('status', 'declined'), _negated=True), _connector='OR'), name='invitation_declined_iff_recorded'),
        ),
    ]
