# Generated by Django 5.2.17 on 2026-10-06 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0009_idea_team_visibility'),
        ('organizations', '0003_idea_review_permission_and_reviewer_role'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('automation_goal', models.TextField(blank=True)),
                ('expected_benefit', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('discovery', 'Discovery'), ('requirements', 'Requirements'), ('solution_design', 'Solution design'), ('proposal', 'Proposal'), ('ready_for_assignment', 'Ready for assignment'), ('assigned', 'Assigned'), ('project_created', 'Project created'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('submission_context', models.CharField(max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, help_text="When the owner's go-ahead was given.", null=True)),
                ('ready_at', models.DateTimeField(blank=True, help_text='When it became ready for assignment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_automation_opportunities', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_opportunities', to='ideas.idea')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_opportunities', to='organizations.organization')),
                ('owner', models.ForeignKey(help_text="The idea's author, who stays its stakeholder throughout delivery.", on_delete=django.db.models.deletion.PROTECT, related_name='owned_automation_opportunities', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_opportunities', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('opportunity_created', 'Opportunity created'), ('opportunity_updated', 'Opportunity updated'), ('opportunity_status_changed', 'Opportunity status changed'), ('requirement_created', 'Requirement created'), ('requirement_updated', 'Requirement updated'), ('solution_updated', 'Solution updated')], max_length=32)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='The authenticated caller; never an input.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='automation.automationopportunity')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'permissions': [('manage_delivery', 'Can run the automation delivery lifecycle across organizations')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('business', 'Business'), ('functional', 'Functional'), ('technical', 'Technical'), ('security', 'Security'), ('integration', 'Integration'), ('data', 'Data'), ('compliance', 'Compliance')], default='functional', max_length=16)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('satisfied', 'Satisfied'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='automation.automationopportunity')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SolutionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('business_workflow', models.TextField(blank=True)),
                ('in_scope', models.TextField(blank=True)),
                ('out_of_scope', models.TextField(blank=True)),
                ('systems_integrations', models.TextField(blank=True)),
                ('technical_considerations', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='automation.automationopportunity')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='automationopportunity',
            index=models.Index(fields=['status', '-created_at'], name='opp_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='automationopportunity',
            index=models.Index(fields=['organization', '-created_at'], name='opp_org_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationopportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('idea',), name='opportunity_one_live_per_idea'),
        ),
        migrations.AddConstraint(
            model_name='automationopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'assigned': 'Assigned', 'cancelled': 'Cancelled', 'completed': 'Completed', 'discovery': 'Discovery', 'draft': 'Draft', 'project_created': 'Project created', 'proposal': 'Proposal', 'ready_for_assignment': 'Ready for assignment', 'requirements': 'Requirements', 'solution_design': 'Solution design'})), name='opportunity_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='automationopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', {'high': 'High', 'low': 'Low', 'medium': 'Medium'})), name='opportunity_priority_is_known'),
        ),
        migrations.AddConstraint(
            model_name='automationopportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('submission_context', 'individual'), ('team__isnull', True)), models.Q(('organization__isnull', True), ('submission_context', 'team'), ('team__isnull', False)), models.Q(('organization__isnull', False), ('submission_context', 'organization'), ('team__isnull', True)), _connector='OR'), name='opportunity_context_matches_tenant'),
        ),
        migrations.AddIndex(
            model_name='opportunityevent',
            index=models.Index(fields=['opportunity', 'created_at'], name='oppevent_opp_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', {'opportunity_created': 'Opportunity created', 'opportunity_status_changed': 'Opportunity status changed', 'opportunity_updated': 'Opportunity updated', 'requirement_created': 'Requirement created', 'requirement_updated': 'Requirement updated', 'solution_updated': 'Solution updated'})), name='opportunity_event_action_is_known'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['opportunity', 'created_at'], name='req_opp_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', {'business': 'Business', 'compliance': 'Compliance', 'data': 'Data', 'functional': 'Functional', 'integration': 'Integration', 'security': 'Security', 'technical': 'Technical'})), name='requirement_type_is_known'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', {'high': 'High', 'low': 'Low', 'medium': 'Medium'})), name='requirement_priority_is_known'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'in_progress': 'In progress', 'open': 'Open', 'rejected': 'Rejected', 'satisfied': 'Satisfied'})), name='requirement_status_is_known'),
        ),
    ]
