# Generated by Django 5.2.17 on 2026-10-06 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('organizations', '0003_idea_review_permission_and_reviewer_role'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-assigned_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=60)),
                ('version', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('successful', 'Successful'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='pending', max_length=12)),
                ('deployment_date', models.DateTimeField(blank=True, null=True)),
                ('deployment_notes', models.TextField(blank=True)),
                ('rollback_information', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the successful deployment was verified in place.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ImpactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('pending', 'Pending'), ('unavailable', 'Unavailable')], default='pending', max_length=12)),
                ('before_processing_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('after_processing_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('before_people_involved', models.PositiveIntegerField(blank=True, null=True)),
                ('after_people_involved', models.PositiveIntegerField(blank=True, null=True)),
                ('before_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('after_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('before_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('after_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('before_error_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('after_error_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('before_workload_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('after_workload_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('users_affected', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_hours_saved_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('measured_hours_saved_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_cost_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('measured_cost_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('automation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qualitative_outcome', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('testing', 'Testing'), ('uat', 'UAT'), ('deployed', 'Deployed'), ('completed', 'Completed'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], default='planning', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('executive_summary', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('proposed_solution', models.TextField(blank=True)),
                ('requirements_summary', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('estimated_effort', models.CharField(blank=True, max_length=120)),
                ('estimated_timeline', models.CharField(blank=True, max_length=120)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=12)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('expected_result', models.TextField(blank=True)),
                ('actual_result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_run', 'Not run'), ('pass', 'Pass'), ('fail', 'Fail'), ('blocked', 'Blocked')], default='not_run', max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UATRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField()),
                ('expected_outcome', models.TextField(blank=True)),
                ('actual_outcome', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('is_required', models.BooleanField(default=True)),
                ('feedback', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='opportunityevent',
            options={'default_permissions': (), 'ordering': ['created_at', 'pk'], 'permissions': [('manage_delivery', 'Can run the automation delivery lifecycle across organizations'), ('be_assignable', 'Can be assigned automation delivery work')]},
        ),
        migrations.RemoveConstraint(
            model_name='opportunityevent',
            name='opportunity_event_action_is_known',
        ),
        migrations.AlterField(
            model_name='opportunityevent',
            name='action',
            field=models.CharField(choices=[('opportunity_created', 'Opportunity created'), ('opportunity_updated', 'Opportunity updated'), ('opportunity_status_changed', 'Opportunity status changed'), ('requirement_created', 'Requirement created'), ('requirement_updated', 'Requirement updated'), ('solution_updated', 'Solution updated'), ('proposal_created', 'Proposal created'), ('proposal_updated', 'Proposal updated'), ('proposal_status_changed', 'Proposal status changed'), ('assignment_created', 'Assignment created'), ('project_created', 'Project created'), ('project_status_changed', 'Project status changed'), ('milestone_created', 'Milestone created'), ('milestone_completed', 'Milestone completed'), ('task_created', 'Task created'), ('task_status_changed', 'Task status changed'), ('test_case_created', 'Test case created'), ('test_executed', 'Test executed'), ('uat_recorded', 'UAT recorded'), ('deployment_recorded', 'Deployment recorded'), ('deployment_verified', 'Deployment verified'), ('impact_recorded', 'Impact recorded')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='opportunityevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', {'assignment_created': 'Assignment created', 'deployment_recorded': 'Deployment recorded', 'deployment_verified': 'Deployment verified', 'impact_recorded': 'Impact recorded', 'milestone_completed': 'Milestone completed', 'milestone_created': 'Milestone created', 'opportunity_created': 'Opportunity created', 'opportunity_status_changed': 'Opportunity status changed', 'opportunity_updated': 'Opportunity updated', 'project_created': 'Project created', 'project_status_changed': 'Project status changed', 'proposal_created': 'Proposal created', 'proposal_status_changed': 'Proposal status changed', 'proposal_updated': 'Proposal updated', 'requirement_created': 'Requirement created', 'requirement_updated': 'Requirement updated', 'solution_updated': 'Solution updated', 'task_created': 'Task created', 'task_status_changed': 'Task status changed', 'test_case_created': 'Test case created', 'test_executed': 'Test executed', 'uat_recorded': 'UAT recorded'})), name='opportunity_event_action_is_known'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignee_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to='teams.team'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='automation.automationopportunity'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactrecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_projects', to='teams.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='automation.assignment'),
        ),
        migrations.AddField(
            model_name='project',
            name='opportunity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='automation.automationopportunity'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_projects', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_projects', to='teams.team'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='automation.project'),
        ),
        migrations.AddField(
            model_name='impactrecord',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='automation.project'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='automation.project'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='opportunity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='automation.automationopportunity'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='automation.milestone'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='automation.project'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='automation.project'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uatrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uat_records', to='automation.project'),
        ),
        migrations.AddField(
            model_name='uatrecord',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('opportunity',), name='assignment_one_active_per_opportunity'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignee_team__isnull', True), ('assignee_user__isnull', False)), models.Q(('assignee_team__isnull', False), ('assignee_user__isnull', True)), _connector='OR'), name='assignment_exactly_one_assignee'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'active': 'Active', 'released': 'Released'})), name='assignment_status_is_known'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='project_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'active': 'Active', 'cancelled': 'Cancelled', 'completed': 'Completed', 'deployed': 'Deployed', 'on_hold': 'On hold', 'planning': 'Planning', 'testing': 'Testing', 'uat': 'UAT'})), name='project_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_team__isnull', True), ('assigned_user__isnull', False)), models.Q(('assigned_team__isnull', False), ('assigned_user__isnull', True)), _connector='OR'), name='project_exactly_one_assignee'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('status', 'completed'), _negated=True), _connector='OR'), name='project_completed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'completed': 'Completed', 'in_progress': 'In progress', 'pending': 'Pending'})), name='milestone_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='impactrecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'pending': 'Pending', 'recorded': 'Recorded', 'unavailable': 'Unavailable'})), name='impact_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'failed': 'Failed', 'in_progress': 'In progress', 'pending': 'Pending', 'rolled_back': 'Rolled back', 'successful': 'Successful'})), name='deployment_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'accepted': 'Accepted', 'changes_requested': 'Changes requested', 'draft': 'Draft', 'ready': 'Ready', 'rejected': 'Rejected', 'submitted': 'Submitted'})), name='proposal_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'blocked': 'Blocked', 'done': 'Done', 'in_progress': 'In progress', 'todo': 'To do'})), name='task_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', {'high': 'High', 'low': 'Low', 'medium': 'Medium'})), name='task_priority_is_known'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'blocked': 'Blocked', 'fail': 'Fail', 'not_run': 'Not run', 'pass': 'Pass'})), name='test_case_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='uatrecord',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', {'failed': 'Failed', 'passed': 'Passed', 'pending': 'Pending'})), name='uat_result_is_known'),
        ),
    ]
