# Generated by Django 5.2.17 on 2026-09-28 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(help_text="1 for an idea's first review, then one more per resubmission.")),
                ('decision', models.CharField(blank=True, choices=[('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved')], help_text='Null while the review is in progress.', max_length=32, null=True)),
                ('feedback', models.TextField(blank=True, help_text="The reviewer's message to the author.")),
                ('submission_snapshot', models.JSONField(help_text="The idea's content as it was when this review started, so a later edit never changes what an earlier review was about.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the decision was recorded. Null while the review is in progress.', null=True)),
                ('idea', models.ForeignKey(db_index=False, help_text="The idea under review, and through it the review's tenant.", on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ideas.idea')),
                ('reviewer', models.ForeignKey(db_index=False, help_text='The member accountable for this review.', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['idea', 'round'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCriterionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(choices=[('problem_clarity', 'Problem clarity'), ('automation_suitability', 'Automation suitability'), ('feasibility', 'Feasibility'), ('expected_benefit', 'Expected benefit'), ('evidence', 'Evidence')], max_length=32)),
                ('rating', models.CharField(choices=[('meets', 'Meets'), ('partially_meets', 'Partially meets'), ('does_not_meet', 'Does not meet'), ('not_applicable', 'Not applicable')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='reviews.review')),
            ],
            options={
                'ordering': ['review', 'criterion'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', '-created_at'], name='reviews_reviewer_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('idea', 'round'), name='review_round_unique_per_idea'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('idea',), name='review_one_open_per_idea'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('round__gte', 1)), name='review_round_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('decision__isnull', True)), models.Q(('completed_at__isnull', False), ('decision__isnull', False)), _connector='OR'), name='review_decided_iff_completed'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('decision__isnull', True), ('decision__in', {'approved': 'Approved', 'changes_requested': 'Changes requested', 'rejected': 'Rejected'}), _connector='OR'), name='review_decision_is_known'),
        ),
        migrations.AddConstraint(
            model_name='reviewcriterionassessment',
            constraint=models.UniqueConstraint(fields=('review', 'criterion'), name='assessment_criterion_unique_per_review'),
        ),
        migrations.AddConstraint(
            model_name='reviewcriterionassessment',
            constraint=models.CheckConstraint(condition=models.Q(('criterion__in', {'automation_suitability': 'Automation suitability', 'evidence': 'Evidence', 'expected_benefit': 'Expected benefit', 'feasibility': 'Feasibility', 'problem_clarity': 'Problem clarity'})), name='assessment_criterion_is_known'),
        ),
        migrations.AddConstraint(
            model_name='reviewcriterionassessment',
            constraint=models.CheckConstraint(condition=models.Q(('rating__in', {'does_not_meet': 'Does not meet', 'meets': 'Meets', 'not_applicable': 'Not applicable', 'partially_meets': 'Partially meets'})), name='assessment_rating_is_known'),
        ),
    ]
