# Generated by Django 5.2.17 on 2026-09-28 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideatransition'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_decision_is_known',
        ),
        migrations.AlterField(
            model_name='review',
            name='decision',
            field=models.CharField(blank=True, choices=[('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('withdrawn', 'Withdrawn')], help_text='Null while the review is in progress.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='round',
            field=models.PositiveSmallIntegerField(help_text="1 for an idea's first review, then one more per resubmission or take-over."),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('decision__isnull', True), ('decision__in', {'approved': 'Approved', 'changes_requested': 'Changes requested', 'rejected': 'Rejected', 'withdrawn': 'Withdrawn'}), _connector='OR'), name='review_decision_is_known'),
        ),
    ]
