# Generated by Django 5.2.17 on 2026-10-03 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_idea_submission_context_constraints'),
        ('organizations', '0003_idea_review_permission_and_reviewer_role'),
        ('reviews', '0002_review_withdrawn_decision'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_context', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('organization', 'Organization')], max_length=16)),
                ('round', models.PositiveSmallIntegerField(help_text='The platform review round this report describes. Copied from the review.')),
                ('decision', models.CharField(choices=[('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn')], default='approved', help_text='Always `approved`. Copied from the review so the report is self-contained.', max_length=32)),
                ('review_summary', models.TextField(blank=True, help_text="The reviewer's overview of the submission.")),
                ('recommendations', models.TextField(blank=True)),
                ('important_considerations', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('approval_summary', models.TextField(blank=True, help_text='Why the platform approved it, and what approval means at this stage.')),
                ('criteria', models.JSONField(blank=True, default=list, help_text='The categorical criterion assessments, copied from the review: criterion, rating and note for each. Never a score.')),
                ('approved_at', models.DateTimeField(help_text='Copied from the approving review. Never generated on a schedule.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'review assignments',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_one_open_per_idea',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_decision_is_known',
        ),
        migrations.AddField(
            model_name='review',
            name='scope',
            field=models.CharField(choices=[('organization', 'Organization review'), ('platform', 'Platform review')], default='platform', help_text='Whether this is the organization confirming what it wants to submit, or the platform reviewing the submission. Never inferred from the idea: the two are decided by different people under different rules.', max_length=16),
        ),
        migrations.AlterField(
            model_name='review',
            name='decision',
            field=models.CharField(blank=True, choices=[('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn')], help_text='Null while the review is in progress.', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('idea', 'scope'), name='review_one_open_per_idea_scope'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('decision__isnull', True), ('decision__in', {'approved': 'Approved', 'changes_requested': 'Changes requested', 'confirmed': 'Confirmed', 'rejected': 'Rejected', 'withdrawn': 'Withdrawn'}), _connector='OR'), name='review_decision_is_known'),
        ),
        migrations.AddField(
            model_name='platformreviewreport',
            name='idea',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='platform_reports', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='platformreviewreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_reports', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='platformreviewreport',
            name='review',
            field=models.OneToOneField(help_text='The platform review that approved this idea.', on_delete=django.db.models.deletion.PROTECT, related_name='report', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='platformreviewreport',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_reports', to='teams.team'),
        ),
        migrations.AddField(
            model_name='platformreviewreport',
            name='version',
            field=models.ForeignKey(help_text='The frozen submission this report is about.', on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='ideas.ideasubmissionversion'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_review_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='idea',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformreviewreport',
            index=models.Index(fields=['idea', '-generated_at'], name='reports_idea_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformreviewreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'approved'), _negated=True), ('submission_context', 'individual'), ('submission_context', 'team'), ('submission_context', 'organization'), _connector='OR'), name='report_is_for_a_platform_approval'),
        ),
        migrations.AddConstraint(
            model_name='platformreviewreport',
            constraint=models.CheckConstraint(condition=models.Q(('round__gte', 1)), name='report_round_is_positive'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['idea', '-created_at'], name='assignments_idea_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['reviewer', '-created_at'], name='assignments_reviewer_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('idea',), name='review_one_current_assignment_per_idea'),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewer', models.F('assigned_by')), _negated=True), ('released_at__isnull', False), _connector='OR'), name='assignment_reviewer_is_not_itself_unless_released'),
        ),
    ]
