# Generated by Django 5.2.17 on 2026-10-04 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_idea_submission_context_constraints'),
        ('reviews', '0003_review_scope_and_platform_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['idea', 'scope', 'round']},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_round_unique_per_idea',
        ),
        migrations.AlterField(
            model_name='review',
            name='round',
            field=models.PositiveSmallIntegerField(help_text="1 for this scope's first review of this idea, then one more per resubmission or take-over. Numbered **per scope**, so a platform report can honestly say 'platform review round 2'."),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('idea', 'scope', 'round'), name='review_round_unique_per_idea_scope'),
        ),
    ]
