# Generated by Django 5.2.17 on 2026-10-07 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_rounds_per_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='Who recorded the decision, when that is not `reviewer`: in a review team any member may send changes back, so the person who did is kept.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_review_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='team',
            field=models.ForeignKey(blank=True, help_text="Set when the idea was routed to a review team. `reviewer` is then the team's lead at the time: the one accountable name on the decision.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='reviews.reviewteam'),
        ),
        migrations.CreateModel(
            name='ReviewTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reviews.reviewteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='review_team_member_unique')],
            },
        ),
    ]
