# Generated by Django 5.2.17 on 2026-10-07 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_audience_follows_level'),
        ('reviews', '0005_review_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('executive_summary', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('proposed_solution', models.TextField(blank=True)),
                ('requirements_summary', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('estimated_effort', models.CharField(blank=True, max_length=120)),
                ('estimated_timeline', models.CharField(blank=True, max_length=120)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to the platform admin'), ('changes_requested', 'Changes requested'), ('released', 'Released to the owner'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='ideas.idea')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='The review team that wrote it; empty when a single reviewer did.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='reviews.reviewteam')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaProposalView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='reviews.ideaproposal')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='ideaproposal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'changes_requested': 'Changes requested', 'declined': 'Declined', 'draft': 'Draft', 'released': 'Released to the owner', 'submitted': 'Submitted to the platform admin'})), name='idea_proposal_status_is_known'),
        ),
    ]
