# Generated by Django 5.2.17 on 2026-10-07 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_idea_proposals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaProposalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Started'), ('edited', 'Edited'), ('submitted', 'Sent to the admin')], max_length=20)),
                ('sections', models.JSONField(blank=True, default=list, help_text='The proposal fields an edit changed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='reviews.ideaproposal')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
