# Generated by Django 5.2.17 on 2026-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_proposal_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaproposal',
            name='feasibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideaproposal',
            name='financial_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideaproposal',
            name='milestones',
            field=models.TextField(blank=True, help_text='The timeline, phase by phase.'),
        ),
        migrations.AddField(
            model_name='ideaproposal',
            name='payment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideaproposal',
            name='payment_required',
            field=models.CharField(blank=True, choices=[('yes', 'The owner pays'), ('no', 'No charge to the owner')], help_text='Whether the owner pays for it; empty until the team answers.', max_length=3),
        ),
    ]
