# Generated by Django 5.2.17 on 2026-10-08 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_audience_follows_level'),
        ('reviews', '0008_proposal_feasibility_and_finance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Waiting to be sent'), ('sent', 'Sent to the owner')], default='pending', max_length=16)),
                ('message', models.TextField(blank=True, help_text='The letter as sent. Drafted from a template; the administrator may edit it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_letters', to='ideas.idea')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_letter', to='reviews.review')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['idea', 'status'], name='decision_letter_idea_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', True), ('sent_by__isnull', True), ('status', 'pending')), models.Q(('sent_at__isnull', False), ('sent_by__isnull', False), ('status', 'sent')), _connector='OR'), name='decision_letter_sent_fields_match_status')],
            },
        ),
    ]
