# Generated by Django 5.2.17 on 2026-10-08 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_audience_follows_level'),
        ('reviews', '0009_decision_letters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_responses', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_responses', to='ideas.idea')),
                ('review', models.OneToOneField(help_text='The completed round that asked for the changes.', on_delete=django.db.models.deletion.CASCADE, related_name='change_response', to='reviews.review')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
