# Generated by Django 5.2.17 on 2026-10-08 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_audience_follows_level'),
        ('reviews', '0010_change_responses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('proceed', 'Go ahead with development'), ('decline', 'Do not go ahead')], max_length=16)),
                ('timeline', models.CharField(blank=True, choices=[('yes', 'Agreed'), ('discuss', 'Needs discussion')], help_text='Whether the owner accepts the proposed timeline. Blank for a decline.', max_length=16)),
                ('payment', models.CharField(blank=True, choices=[('yes', 'Agreed'), ('discuss', 'Needs discussion')], help_text='Whether the owner accepts the payment plan. Blank when there is no charge.', max_length=16)),
                ('preferred_start', models.DateField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, help_text='Anything the delivery team should know before starting.')),
                ('decline_reason', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_answers', to='ideas.idea')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_answer', to='reviews.ideaproposal')),
            ],
        ),
    ]
