# Generated by Django 5.2.17 on 2026-09-29 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('membership_role.assigned', 'Organization role assigned'), ('membership_role.removed', 'Organization role removed'), ('category.created', 'Category created'), ('category.updated', 'Category updated'), ('category.activated', 'Category activated'), ('category.deactivated', 'Category deactivated'), ('attachment.downloaded', 'Attachment downloaded'), ('platform_admin.granted', 'Platform administration granted'), ('platform_admin.revoked', 'Platform administration revoked')], max_length=64)),
                ('result', models.CharField(choices=[('succeeded', 'Succeeded'), ('refused', 'Refused')], max_length=16)),
                ('target_type', models.CharField(help_text="e.g. 'user', 'category'.", max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, help_text='For a refusal, the reason given to the administrator.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The authenticated administrator. Null only for command-line operations.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'admin audit entries',
                'ordering': ['-created_at', '-pk'],
                'permissions': [('access_console', 'Can access the platform administration console'), ('inspect_idea_content', 'Can inspect idea content, discussion, evidence and review feedback across organizations'), ('manage_user_accounts', 'Can activate and deactivate user accounts'), ('manage_organization_roles', 'Can assign and remove organization roles'), ('manage_categories', 'Can create, edit and retire idea categories')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['-created_at'], name='admin_audit_created_idx'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='admin_audit_target_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', {'attachment.downloaded': 'Attachment downloaded', 'category.activated': 'Category activated', 'category.created': 'Category created', 'category.deactivated': 'Category deactivated', 'category.updated': 'Category updated', 'membership_role.assigned': 'Organization role assigned', 'membership_role.removed': 'Organization role removed', 'platform_admin.granted': 'Platform administration granted', 'platform_admin.revoked': 'Platform administration revoked', 'user.activated': 'User activated', 'user.deactivated': 'User deactivated'})), name='admin_audit_action_is_known'), models.CheckConstraint(condition=models.Q(('result__in', {'refused': 'Refused', 'succeeded': 'Succeeded'})), name='admin_audit_result_is_known')],
            },
        ),
    ]
