# Generated by Django 5.2.17 on 2026-10-08 02:15

from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations, models

PLATFORM_ADMIN_GROUP = 'Platform administrators'
#: The staffing permissions the administrators' group now holds (see `CONSOLE_PERMISSIONS`).
STAFFING = ('manage_reviewers', 'manage_platform_roles')


def give_administrators_staffing(apps, schema_editor):
    """
    Add the staffing permissions to an existing "Platform administrators" group, so the
    administrators already granted can open the Reviewers and Platform roles pages without
    re-running `grant_platform_admin`. Permissions are normally created after migrating;
    the new one is created here first so it can be added.
    """
    app_config = apps.get_app_config('administration')
    # A migration's app registry holds stubs without `models_module`, which
    # `create_permissions` checks; the stub is set for the call and put back after.
    app_config.models_module = True
    create_permissions(app_config, verbosity=0, apps=apps)
    app_config.models_module = None
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    group = Group.objects.filter(name=PLATFORM_ADMIN_GROUP).first()
    if group is None:
        return
    group.permissions.add(
        *Permission.objects.filter(content_type__app_label='administration', codename__in=STAFFING)
    )


def take_back_staffing(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    group = Group.objects.filter(name=PLATFORM_ADMIN_GROUP).first()
    if group is not None:
        group.permissions.remove(
            *Permission.objects.filter(
                content_type__app_label='administration', codename__in=STAFFING
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_idea_proposals'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminauditentry',
            options={'default_permissions': (), 'ordering': ['-created_at', '-pk'], 'permissions': [('access_console', 'Can access the platform administration console'), ('inspect_idea_content', 'Can inspect idea content, discussion, evidence and review feedback across organizations'), ('manage_user_accounts', 'Can activate and deactivate user accounts'), ('manage_organization_roles', 'Can assign and remove organization roles'), ('manage_categories', 'Can create, edit and retire idea categories'), ('review_platform_submissions', 'Can inspect, review and decide ideas submitted to the platform'), ('assign_platform_reviewers', 'Can assign and remove the platform reviewer of a submission'), ('manage_reviewers', 'Can create and remove platform reviewers and form review teams'), ('release_proposals', "Can approve a review team's proposal and release it to the idea owner"), ('manage_platform_roles', 'Can give accounts platform roles: developer, delivery manager, intake and proposal approver')], 'verbose_name_plural': 'admin audit entries'},
        ),
        migrations.RemoveConstraint(
            model_name='adminauditentry',
            name='admin_audit_action_is_known',
        ),
        migrations.AlterField(
            model_name='adminauditentry',
            name='action',
            field=models.CharField(choices=[('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('membership_role.assigned', 'Organization role assigned'), ('membership_role.removed', 'Organization role removed'), ('category.created', 'Category created'), ('category.updated', 'Category updated'), ('category.activated', 'Category activated'), ('category.deactivated', 'Category deactivated'), ('attachment.downloaded', 'Attachment downloaded'), ('platform_admin.granted', 'Platform administration granted'), ('platform_admin.revoked', 'Platform administration revoked'), ('platform_reviewer.assigned', 'Platform reviewer assigned'), ('platform_reviewer.unassigned', 'Platform reviewer unassigned'), ('platform_submission.locked', 'Platform submission locked'), ('platform_review.approved', 'Platform review approved'), ('platform_review.changes_requested', 'Platform review requested changes'), ('platform_review.rejected', 'Platform review rejected'), ('report.generated', 'Platform review report generated'), ('idea.owner_go_ahead', 'Idea owner gave go-ahead'), ('reviewer.granted', 'Platform reviewer created'), ('reviewer.revoked', 'Platform reviewer removed'), ('review_team.created', 'Review team created'), ('review_team.updated', 'Review team changed'), ('review_team.assigned', 'Idea assigned to a review team'), ('proposal.submitted', 'Proposal submitted to the platform admin'), ('proposal.changes_requested', 'Proposal sent back to the review team'), ('proposal.released', 'Proposal released to its owner'), ('proposal.declined', 'Proposal declined'), ('platform_role.granted', 'Platform role given'), ('platform_role.revoked', 'Platform role removed')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='adminauditentry',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', {'attachment.downloaded': 'Attachment downloaded', 'category.activated': 'Category activated', 'category.created': 'Category created', 'category.deactivated': 'Category deactivated', 'category.updated': 'Category updated', 'idea.owner_go_ahead': 'Idea owner gave go-ahead', 'membership_role.assigned': 'Organization role assigned', 'membership_role.removed': 'Organization role removed', 'platform_admin.granted': 'Platform administration granted', 'platform_admin.revoked': 'Platform administration revoked', 'platform_review.approved': 'Platform review approved', 'platform_review.changes_requested': 'Platform review requested changes', 'platform_review.rejected': 'Platform review rejected', 'platform_reviewer.assigned': 'Platform reviewer assigned', 'platform_reviewer.unassigned': 'Platform reviewer unassigned', 'platform_role.granted': 'Platform role given', 'platform_role.revoked': 'Platform role removed', 'platform_submission.locked': 'Platform submission locked', 'proposal.changes_requested': 'Proposal sent back to the review team', 'proposal.declined': 'Proposal declined', 'proposal.released': 'Proposal released to its owner', 'proposal.submitted': 'Proposal submitted to the platform admin', 'report.generated': 'Platform review report generated', 'review_team.assigned': 'Idea assigned to a review team', 'review_team.created': 'Review team created', 'review_team.updated': 'Review team changed', 'reviewer.granted': 'Platform reviewer created', 'reviewer.revoked': 'Platform reviewer removed', 'user.activated': 'User activated', 'user.deactivated': 'User deactivated'})), name='admin_audit_action_is_known'),
        ),
        migrations.RunPython(give_administrators_staffing, take_back_staffing),
    ]
