# Generated by Django 5.2.17 on 2026-10-08 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_console_is_for_administrators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adminauditentry',
            name='admin_audit_action_is_known',
        ),
        migrations.AlterField(
            model_name='adminauditentry',
            name='action',
            field=models.CharField(choices=[('user.activated', 'User activated'), ('user.deactivated', 'User deactivated'), ('membership_role.assigned', 'Organization role assigned'), ('membership_role.removed', 'Organization role removed'), ('category.created', 'Category created'), ('category.updated', 'Category updated'), ('category.activated', 'Category activated'), ('category.deactivated', 'Category deactivated'), ('attachment.downloaded', 'Attachment downloaded'), ('platform_admin.granted', 'Platform administration granted'), ('platform_admin.revoked', 'Platform administration revoked'), ('platform_reviewer.assigned', 'Platform reviewer assigned'), ('platform_reviewer.unassigned', 'Platform reviewer unassigned'), ('platform_submission.locked', 'Platform submission locked'), ('platform_review.approved', 'Platform review approved'), ('platform_review.changes_requested', 'Platform review requested changes'), ('platform_review.rejected', 'Platform review rejected'), ('report.generated', 'Platform review report generated'), ('idea.owner_go_ahead', 'Idea owner gave go-ahead'), ('reviewer.granted', 'Platform reviewer created'), ('reviewer.revoked', 'Platform reviewer removed'), ('review_team.created', 'Review team created'), ('review_team.updated', 'Review team changed'), ('review_team.assigned', 'Idea assigned to a review team'), ('proposal.submitted', 'Proposal submitted to the platform admin'), ('proposal.changes_requested', 'Proposal sent back to the review team'), ('proposal.released', 'Proposal released to its owner'), ('proposal.declined', 'Proposal declined'), ('platform_role.granted', 'Platform role given'), ('platform_role.revoked', 'Platform role removed'), ('decision_letter.sent', 'Decision letter sent to the owner')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='adminauditentry',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', {'attachment.downloaded': 'Attachment downloaded', 'category.activated': 'Category activated', 'category.created': 'Category created', 'category.deactivated': 'Category deactivated', 'category.updated': 'Category updated', 'decision_letter.sent': 'Decision letter sent to the owner', 'idea.owner_go_ahead': 'Idea owner gave go-ahead', 'membership_role.assigned': 'Organization role assigned', 'membership_role.removed': 'Organization role removed', 'platform_admin.granted': 'Platform administration granted', 'platform_admin.revoked': 'Platform administration revoked', 'platform_review.approved': 'Platform review approved', 'platform_review.changes_requested': 'Platform review requested changes', 'platform_review.rejected': 'Platform review rejected', 'platform_reviewer.assigned': 'Platform reviewer assigned', 'platform_reviewer.unassigned': 'Platform reviewer unassigned', 'platform_role.granted': 'Platform role given', 'platform_role.revoked': 'Platform role removed', 'platform_submission.locked': 'Platform submission locked', 'proposal.changes_requested': 'Proposal sent back to the review team', 'proposal.declined': 'Proposal declined', 'proposal.released': 'Proposal released to its owner', 'proposal.submitted': 'Proposal submitted to the platform admin', 'report.generated': 'Platform review report generated', 'review_team.assigned': 'Idea assigned to a review team', 'review_team.created': 'Review team created', 'review_team.updated': 'Review team changed', 'reviewer.granted': 'Platform reviewer created', 'reviewer.revoked': 'Platform reviewer removed', 'user.activated': 'User activated', 'user.deactivated': 'User deactivated'})), name='admin_audit_action_is_known'),
        ),
    ]
