# Generated by Django 5.2.17 on 2026-10-03 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0006_idea_submission_context_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Optional. Defaults to the idea title, or is left blank for a direct message.', max_length=200)),
                ('latest_message_at', models.DateTimeField(help_text='When the last message was posted. Null until then - never null on a real thread.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(blank=True, help_text='Context only. Read access comes from the participant list, never from this.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='ideas.idea')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_message_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-latest_message_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MessageParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_participants', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.messagethread')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='msgpart_user_created_idx'), models.Index(fields=['thread', 'user'], name='msgpart_thread_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('thread', 'user'), name='unique_message_participant_per_thread')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.messagethread')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='messages_thread_created_idx'), models.Index(fields=['sender', '-created_at'], name='messages_sender_created_idx')],
            },
        ),
    ]
