# Generated by Django 5.2.17 on 2026-09-26 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_permission_role_membershiprole_rolepermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Unset to retire a category from new ideas without touching existing ones.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('proposed_solution', models.TextField(blank=True)),
                ('expected_benefit', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('automation_proposal', 'Automation proposal')], default='draft', max_length=32)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('organization', 'Organization'), ('department', 'Department'), ('private', 'Private')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(db_index=False, help_text='The member who submitted this idea.', on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, db_index=False, help_text='Optional: an idea can be drafted before it is classified.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='ideas.category')),
                ('organization', models.ForeignKey(db_index=False, help_text='The owning organization. Required: an idea never exists outside a tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_comments', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ideas.idea')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(help_text='MIME type as reported at upload, e.g. image/png.', max_length=255)),
                ('size', models.PositiveBigIntegerField(help_text='Size in bytes.')),
                ('storage_key', models.CharField(help_text='Key of the object in storage. The bytes live there, never in PostgreSQL.', max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_attachments', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ideas.idea')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ideas.idea')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='idea_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['organization', '-created_at'], name='ideas_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['organization', 'status'], name='ideas_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['category', '-created_at'], name='ideas_category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['visibility', '-created_at'], name='ideas_vis_created_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['author', '-created_at'], name='ideas_author_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'approved': 'Approved', 'automation_proposal': 'Automation proposal', 'changes_requested': 'Changes requested', 'draft': 'Draft', 'rejected': 'Rejected', 'submitted': 'Submitted', 'under_review': 'Under review'})), name='idea_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', {'department': 'Department', 'organization': 'Organization', 'private': 'Private', 'public': 'Public'})), name='idea_visibility_is_known'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['idea', 'created_at'], name='comments_idea_created_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['idea', 'created_at'], name='attachments_idea_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'idea'), name='unique_vote_per_user_idea'),
        ),
    ]
