# Generated by Django 5.2.17 on 2026-09-28 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('automation_proposal', 'Automation proposal')], max_length=32)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('automation_proposal', 'Automation proposal')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='The authenticated member who made the move.', on_delete=django.db.models.deletion.PROTECT, related_name='idea_transitions', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='ideas.idea')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['idea', 'created_at'], name='ideas_trans_idea_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_status__in', {'approved': 'Approved', 'automation_proposal': 'Automation proposal', 'changes_requested': 'Changes requested', 'draft': 'Draft', 'rejected': 'Rejected', 'submitted': 'Submitted', 'under_review': 'Under review'})), name='idea_transition_from_is_known'), models.CheckConstraint(condition=models.Q(('to_status__in', {'approved': 'Approved', 'automation_proposal': 'Automation proposal', 'changes_requested': 'Changes requested', 'draft': 'Draft', 'rejected': 'Rejected', 'submitted': 'Submitted', 'under_review': 'Under review'})), name='idea_transition_to_is_known'), models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='idea_transition_changes_status')],
            },
        ),
    ]
