# Generated by Django 5.2.17 on 2026-09-29 04:57

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideatransition'),
        ('organizations', '0003_idea_review_permission_and_reviewer_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='affected_people',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='idea',
            name='current_process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='current_tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('paper_forms', 'Paper forms'), ('excel', 'Excel'), ('google_sheets', 'Google Sheets'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('phone_calls', 'Phone calls'), ('website', 'Website'), ('mobile_app', 'Mobile application'), ('computer_program', 'Computer program'), ('physical_files', 'Physical files'), ('other', 'Other')], max_length=32), blank=True, default=list, help_text='What the work is handled with today (paper, Excel, email...).', size=None),
        ),
        migrations.AddField(
            model_name='idea',
            name='current_tools_other',
            field=models.CharField(blank=True, help_text="Anything else the work is handled with, in the author's words.", max_length=200),
        ),
        migrations.AddField(
            model_name='idea',
            name='desired_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='easier_for_people',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='frequency',
            field=models.CharField(blank=True, choices=[('several_times_a_day', 'Several times a day'), ('daily', 'Daily'), ('several_times_a_week', 'Several times a week'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('occasionally', 'Occasionally'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='idea',
            name='impact_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='impacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('too_much_time', 'It takes too much time'), ('repeated_work', 'People have to repeat the same work'), ('mistakes', 'Mistakes happen'), ('waiting', 'People have to wait'), ('delays', 'Work gets delayed'), ('overload', 'People become overloaded'), ('lost_information', 'Information gets lost'), ('complaints', 'Customers, students or users complain'), ('higher_costs', 'It increases costs'), ('other', 'Other')], max_length=32), blank=True, default=list, help_text='What happens because of the problem.', size=None),
        ),
        migrations.AddField(
            model_name='idea',
            name='important_considerations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='improvement_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='people_involved',
            field=models.PositiveIntegerField(blank=True, help_text='Roughly how many people take part in the process. Null means not answered.', null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='performed_by',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='idea',
            name='time_required',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('frequency', ''), ('frequency__in', {'daily': 'Daily', 'monthly': 'Monthly', 'occasionally': 'Occasionally', 'other': 'Other', 'several_times_a_day': 'Several times a day', 'several_times_a_week': 'Several times a week', 'weekly': 'Weekly'}), _connector='OR'), name='idea_frequency_is_known'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('impacts__contained_by', ['too_much_time', 'repeated_work', 'mistakes', 'waiting', 'delays', 'overload', 'lost_information', 'complaints', 'higher_costs', 'other'])), name='idea_impacts_are_known'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('current_tools__contained_by', ['paper_forms', 'excel', 'google_sheets', 'email', 'whatsapp', 'phone_calls', 'website', 'mobile_app', 'computer_program', 'physical_files', 'other'])), name='idea_current_tools_are_known'),
        ),
    ]
