# Generated by Django 5.2.17 on 2026-10-03 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_comment_replies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaSubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(help_text='1 for the first platform submission, then one more per resubmission.')),
                ('submission_context', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('organization', 'Organization')], help_text='The context at the moment of submission. A copy, because the live row may change.', max_length=16)),
                ('snapshot', models.JSONField(help_text="The idea's content, frozen at the moment of submission.")),
                ('is_current', models.BooleanField(default=False, help_text='Whether the platform is holding this version. Exactly one per idea once submitted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'idea submission versions',
                'ordering': ['idea', 'version'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='idea',
            name='idea_status_is_known',
        ),
        migrations.RemoveConstraint(
            model_name='ideatransition',
            name='idea_transition_from_is_known',
        ),
        migrations.RemoveConstraint(
            model_name='ideatransition',
            name='idea_transition_to_is_known',
        ),
        migrations.AddField(
            model_name='idea',
            name='owner_go_ahead_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='owner_go_ahead_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idea_go_aheads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='platform_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='platform_locked_at',
            field=models.DateTimeField(blank=True, help_text='When the official platform submission was frozen. Never cleared.', null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='platform_version',
            field=models.PositiveSmallIntegerField(default=0, help_text='Version number of the official platform submission. 0 means not submitted.'),
        ),
        migrations.AddField(
            model_name='idea',
            name='submission_context',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('organization', 'Organization')], default='organization', help_text='Who this idea is being put forward by.', max_length=16),
        ),
    ]
