# Generated by Django 5.2.17 on 2026-10-03 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_idea_submission_context'),
        ('organizations', '0003_idea_review_permission_and_reviewer_role'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='team',
            field=models.ForeignKey(blank=True, help_text='The team this idea was filed for, when its submission context is `team`. A team is a collaboration boundary, not a tenant: it never validates the idea and can never approve it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='teams.team'),
        ),
        migrations.AddField(
            model_name='ideasubmissionversion',
            name='idea',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='submission_versions', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='ideasubmissionversion',
            name='submitted_by',
            field=models.ForeignKey(help_text='The member who submitted this version to the platform.', on_delete=django.db.models.deletion.PROTECT, related_name='idea_submission_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='organization',
            field=models.ForeignKey(blank=True, db_index=False, help_text='The organization this idea was filed for, when its submission context is `organization`. Null for an individual or team idea: an idea never exists outside a tenant, but a tenant is not always an organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_to_organization', 'Waiting for organization review'), ('organization_changes_requested', 'Changes requested by organization'), ('organization_confirmed', 'Organization confirmed'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('ready_for_implementation', 'Ready for implementation'), ('automation_proposal', 'Automation proposal')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='ideatransition',
            name='from_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_to_organization', 'Waiting for organization review'), ('organization_changes_requested', 'Changes requested by organization'), ('organization_confirmed', 'Organization confirmed'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('ready_for_implementation', 'Ready for implementation'), ('automation_proposal', 'Automation proposal')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ideatransition',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_to_organization', 'Waiting for organization review'), ('organization_changes_requested', 'Changes requested by organization'), ('organization_confirmed', 'Organization confirmed'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('ready_for_implementation', 'Ready for implementation'), ('automation_proposal', 'Automation proposal')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['team', '-created_at'], name='ideas_team_created_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['author', 'status', '-created_at'], name='ideas_author_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ideasubmissionversion',
            index=models.Index(fields=['idea', 'version'], name='versions_idea_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', {'approved': 'Approved', 'automation_proposal': 'Automation proposal', 'changes_requested': 'Changes requested', 'draft': 'Draft', 'organization_changes_requested': 'Changes requested by organization', 'organization_confirmed': 'Organization confirmed', 'ready_for_implementation': 'Ready for implementation', 'rejected': 'Rejected', 'submitted': 'Submitted', 'submitted_to_organization': 'Waiting for organization review', 'under_review': 'Under review'})), name='idea_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization_id__isnull', True), ('submission_context', 'individual'), ('team_id__isnull', True)), models.Q(('organization_id__isnull', True), ('submission_context', 'team'), ('team_id__isnull', False)), models.Q(('organization_id__isnull', False), ('submission_context', 'organization'), ('team_id__isnull', True)), _connector='OR'), name='idea_submission_context_matches_tenants'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('platform_locked_at__isnull', True), ('platform_version', 0)), models.Q(('platform_locked_at__isnull', False), ('platform_version__gte', 1)), _connector='OR'), name='idea_platform_lock_matches_version'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'ready_for_implementation'), models.Q(('owner_go_ahead_at__isnull', True), ('owner_go_ahead_by__isnull', True)), _connector='OR'), name='idea_go_ahead_only_when_ready'),
        ),
        migrations.AddConstraint(
            model_name='ideasubmissionversion',
            constraint=models.UniqueConstraint(fields=('idea', 'version'), name='version_number_unique_per_idea'),
        ),
        migrations.AddConstraint(
            model_name='ideasubmissionversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('idea',), name='unique_current_version_per_idea'),
        ),
        migrations.AddConstraint(
            model_name='ideasubmissionversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='version_number_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='ideatransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__in', {'approved': 'Approved', 'automation_proposal': 'Automation proposal', 'changes_requested': 'Changes requested', 'draft': 'Draft', 'organization_changes_requested': 'Changes requested by organization', 'organization_confirmed': 'Organization confirmed', 'ready_for_implementation': 'Ready for implementation', 'rejected': 'Rejected', 'submitted': 'Submitted', 'submitted_to_organization': 'Waiting for organization review', 'under_review': 'Under review'})), name='idea_transition_from_is_known'),
        ),
        migrations.AddConstraint(
            model_name='ideatransition',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', {'approved': 'Approved', 'automation_proposal': 'Automation proposal', 'changes_requested': 'Changes requested', 'draft': 'Draft', 'organization_changes_requested': 'Changes requested by organization', 'organization_confirmed': 'Organization confirmed', 'ready_for_implementation': 'Ready for implementation', 'rejected': 'Rejected', 'submitted': 'Submitted', 'submitted_to_organization': 'Waiting for organization review', 'under_review': 'Under review'})), name='idea_transition_to_is_known'),
        ),
    ]
