# Generated by Django 5.2.17 on 2026-10-04 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Let the owner's go-ahead survive the hand-off to the developer track.

    `idea_go_ahead_only_when_ready` said the go-ahead may only be recorded while
    an idea is in `ready_for_implementation`. The lifecycle has
    `READY_FOR_IMPLEMENTATION -> AUTOMATION_PROPOSAL`, so an idea that took that
    hand-off with its go-ahead on the row could not be saved at all - and the
    go-ahead is exactly the record of *who authorized this*, which has to be
    readable after the hand-off rather than before it.

    The constraint is recreated with the same name and a wider set of statuses
    rather than dropped: "an idea cannot be handed to implementation without the
    owner's go-ahead" is still the guarantee, and it is still a database fact.
    """

    dependencies = [
        ('ideas', '0006_idea_submission_context_constraints'),
        ('organizations', '0003_idea_review_permission_and_reviewer_role'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='idea',
            name='idea_go_ahead_only_when_ready',
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('status__in', ['ready_for_implementation', 'automation_proposal']),
                    models.Q(
                        ('owner_go_ahead_at__isnull', True), ('owner_go_ahead_by__isnull', True)
                    ),
                    _connector='OR',
                ),
                name='idea_go_ahead_only_when_ready',
            ),
        ),
    ]
