# Generated by Django 5.2.17 on 2026-10-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Drop the duplicate index on `Idea.team`.

    `ideas_team_created_idx` is `(team, -created_at)`, so the automatic
    single-column index Django puts on a foreign key is a strict prefix of it and
    answers nothing the composite does not. It was paid on every write to `Idea`
    - and this app writes a status change on nearly every read of a review queue.
    Same reason `organization`, `author` and `category` already carry
    `db_index=False`.
    """

    dependencies = [
        ('ideas', '0007_idea_go_ahead_survives_the_developer_handoff'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='team',
            field=models.ForeignKey(blank=True, db_index=False, help_text='The team this idea was filed for, when its submission context is `team`. A team is a collaboration boundary, not a tenant: it never validates the idea and can never approve it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='teams.team'),
        ),
    ]
